### PR TITLE
Feature/travisCI

### LINKED ISSUE #104: ci: run CI on node 7.6, 8 and 10
- [ ] Update Travis build to run build stages
- [ ] Ensure semantic-release is configured to run in the release build stage 
- [ ] Apply changes to all plugins

### PR DESCRIPTION
**Pull request by privateOmega**
Fix #104 
Updated TravisCI configuration to  build using build stages. Semantic-release has been configured to run in the release build stage.

### CODE REVIEW

**Comment by joelmukuthu** [comment]
Awesome @privateOmega, thanks for this! Already we can see there's a bug with node 7.6. I'll find some time soon to look into that.

One thing, about the commit message, following the [commit convention](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) this would be something like `chore(ci): run ci on node 7.6, 8 and 10`

**Comment by privateOmega** [comment]
@joelmukuthu I can change the commit message :+1:

**Comment by joelmukuthu** [comment]
Aah yeah, commitizen has that. I prefer to group them all as chores though, to try and minimise the different types of commits. I'll find some time to document the commit standards I use: https://github.com/knorm/knorm/issues/237

**Comment by privateOmega** [comment]
@joelmukuthu Cool. Will look into it.

**Pull request closed without merging**
