### PR TITLE
chore(ci): run CI on node 8 and 10

### PR DESCRIPTION
**Pull request by privateOmega**
Opened in favour of closed PR #232 .
- Renamed branch.
- Amended commit message to match conventional commit standards.

### CODE REVIEW

**Comment by privateOmega** [comment]
Had to rebase and force push to fix unordered merge commit done by me.

**Comment by joelmukuthu** [comment]
I looked into the failing tests and they are caused by this https://github.com/knorm/knorm/blob/c305b322e4d8406e6ce8bc534143b5532df12bbf/lib/Transaction.js#L26-L27.

So on Node 7.6 the transaction model doesn't inherit that parent model's name. We could fix that by adding a `name` getter function but that's going to slightly impact performance since `Model.name` will now be a function call, even though it's only for transaction models.

I think the performance hit isn't worth the change and in fact I'm thinking to drop support for node 7, since it reached it's end-of-life [back in 2017](https://github.com/nodejs/Release#end-of-life-releases) anyway. This won't be a breaking change since we're not introducing any changes, just choosing to not fix a bug for node 7.

I'll update your PR with the small changes.

**Comment by privateOmega** [comment]
I was wondering whether to add a test stage, but I didn't because you never mentioned anything about that.

**Comment by joelmukuthu** [comment]
@privateOmega that's my bad, I hadn't spec'd out the issue well enough. If you'd like, you're very welcome to ask some questions on the issue you'd like to pick up. I'm a bit swamped by other projects right now but I'll be sure to answer as soon as I can. I really appreciate the contributions.

I'll try to run the different test jobs with different versions of postgres, then I think this is good to go.

**Comment by joelmukuthu** [comment]
Finally got it to work after some more battling.

@privateOmega do you have some time to update the other PRs to look like this? Essentially:

- update .nvmrc to node 10
- run lint, coverage and coveralls only in one test job
- for plugins whose tests use postgres, configure different postgres versions for the different test jobs
- use the latest node version for the release stage

**Comment by privateOmega** [comment]
@joelmukuthu Sure. Will do it when i get time.

**Comment by privateOmega** [comment]
@joelmukuthu I forgot to mention that I had added the code to all the plugins.

**Comment by joelmukuthu** [comment]
Thanks a lot @privateOmega!

**Pull request merged**
